### ISSUE TITLE
Add es module build

### ISSUE THREAD

**Issue by YerkoPalma** [egoist/slugo#2]
Hi 👋 
was trying to use [md](https://github.com/egoist/md) with es modules (no bundlers), like this

```js
import markdown from 'https://unpkg.com/md?module'
```

but I get an error because md import slugo, and the es version import it like this 

```js
import slugo from 'https://unpkg.com/slugo@^0.2.1?module';
```

but slugo has no es build, so it will be really nice to add it. I've actually tried to add it myself but had troubles with [bili ](https://github.com/egoist/bili) :sweat_smile:

**Comment by egoist** [comment]
pr welcome

**Comment by YerkoPalma** [comment]
Well that was my original intention, but, as I said, I had troubles with bili. If I update the build script in package.json to

```
"build": "bili --format umd,cjs,es,umd-min"
```

I get

![image](https://user-images.githubusercontent.com/5105812/44786422-7570a600-ab6a-11e8-8121-6ec881e267d2.png)

That looks like a rollup error, that's why I came here for help. I'll check it again, but if you have any clue it would be awesome

**Comment by egoist** [comment]
Fixed, it's using an older version of bili which doesn't support `-min` yet
