### ISSUE TITLE
Replace duplicate dashes?

### ISSUE THREAD

**Issue by IonicaBizau** [egoist/slugo#4]
I'm wondering if we could replace the duplicated dashes:

```js
> require(".")("2017 — What I learned")
'2017----what-i-learned'
```

I would like `2017-what-i-learned`

**Comment by audiolion** [comment]
you could just add a

```js
slug(slug).replace(/[-]{2,}/, '-')
```

to get the desired behavior

**Comment by jeffreycahyono** [comment]
I think it should be the default implementation, i've tried most starred npm packages: slugify and @sindresorhus/slugify both replace duplicate dashes.
https://codesandbox.io/s/slugify-result-comparison-j11wl?file=/src/index.js

**Comment by egoist** [comment]
PR welcome, btw GitHub seems to transform `2017 — What I learned` to `2017--what-i-learned`

**Comment by egoist** [comment]
This has been changed in v0.4
